static const char html_page[] =
"<!DOCTYPE html>"
"<html lang=\"ru\">"
"<head>"
"  <meta charset=\"UTF-8\">"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"  <title>Управление</title>"
"  <style>"
"    body { font-family: -apple-system, sans-serif; text-align: center; padding: 20px; background: #f5f5f7; }"
"    .container { max-width: 500px; margin: 0 auto; }"
"    #value { font-size: 3rem; font-weight: bold; color: #0071e3; margin: 30px 0; padding: 16px; background: white; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }"
"    .btn { margin: 8px; padding: 12px 24px; font-size: 16px; border: none; border-radius: 8px; cursor: pointer; }"
"    .red { background: #ff3b30; color: white; }"
"    .green { background: #34c759; color: white; }"
"    .blue { background: #0071e3; color: white; }"
"  </style>"
"</head>"
"<body>"
"  <div class=\"container\">"
"    <h2>Данные в реальном времени</h2>"
"    <div id=\"value\">—</div>"
"    <button class=\"btn red\" onclick=\"sendCmd('/cmd1')\">Команда 1</button>"
"    <button class=\"btn green\" onclick=\"sendCmd('/cmd2')\">Команда 2</button>"
"    <button class=\"btn blue\" onclick=\"sendCmd('/cmd3')\">Команда 3</button>"
"  </div>"
""
"  <script>"
"    const valueEl = document.getElementById('value');"
""
"    // Подключаем SSE"
"    const eventSource = new EventSource('/events');"
"    eventSource.onmessage = function(e) {"
"      valueEl.textContent = e.data;"
"    };"
"    eventSource.onerror = function() {"
"      valueEl.textContent = '⚠️ отключено';"
"      eventSource.close();"
"    };"
""
"    // Отправка команд"
"    function sendCmd(url) {"
"      fetch(url, { method: 'GET' })"
"        .then(r => r.text())"
"        .then(msg => console.log('Ответ:', msg))"
"        .catch(err => console.error('Ошибка:', err));"
"    }"
"  </script>"
"</body>"
"</html>";