static const char main_page[] =
"<!DOCTYPE html>\n"
"<html lang=\"ru\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <title>Управление</title>\n"
"  <style>\n"
"    body { font-family: -apple-system, sans-serif; text-align: center; padding: 20px; background: #f5f5f7; }\n"
"    .container { max-width: 500px; margin: 0 auto; }\n"
"    #value { font-size: 1.8rem; font-weight: bold; color: #0071e3; margin: 30px 0; padding: 16px; background: white; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }\n"
"    .btn { margin: 8px; padding: 12px 24px; font-size: 16px; border: none; border-radius: 8px; cursor: pointer; }\n"
"    .red { background: #ff3b30; color: white; }\n"
"    .green { background: #34c759; color: white; }\n"
"    .blue { background: #0071e3; color: white; }\n"
"    #status { font-size: 0.9rem; color: #888; margin-top: 10px; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"container\">\n"
"    <h2>Данные в реальном времени</h2>\n"
"    <div id=\"value\">Ожидание данных…</div>\n"
"    <div id=\"status\"></div>\n"
"    <button class=\"btn red\" onclick=\"sendCmd('/cmd1')\">Команда 1</button>\n"
"    <button class=\"btn green\" onclick=\"sendCmd('/cmd2')\">Команда 2</button>\n"
"    <button class=\"btn blue\" onclick=\"sendCmd('/cmd3')\">Команда 3</button>\n"
"  </div>\n"
"\n"
"  <script>\n"
"    const valueEl = document.getElementById('value');\n"
"    const statusEl = document.getElementById('status');\n"
"\n"
"    // Подключаемся к SSE-потоку\n"
"    const evtSource = new EventSource('/sse');\n"
"\n"
"    evtSource.onmessage = function(e) {\n"
"      valueEl.textContent = e.data;\n"
"      statusEl.textContent = 'Обновлено: ' + new Date().toLocaleTimeString();\n"
"    };\n"
"\n"
"    evtSource.onerror = function() {\n"
"      valueEl.textContent = '—';\n"
"      statusEl.textContent = 'Ошибка подключения к данным';\n"
"      statusEl.style.color = '#ff3b30';\n"
"      // Попытка переподключения не обязательна на ESP32, но можно добавить\n"
"    };\n"
"\n"
"    function sendCmd(url) {\n"
"      fetch(url, { method: 'GET' })\n"
"        .then(r => r.text())\n"
"        .then(msg => {\n"
"          console.log('Ответ:', msg);\n"
"          // Можно показать уведомление, если нужно\n"
"        })\n"
"        .catch(err => {\n"
"          console.error('Ошибка команды:', err);\n"
"          statusEl.textContent = 'Ошибка команды';\n"
"          statusEl.style.color = '#ff3b30';\n"
"        });\n"
"    }\n"
"  </script>\n"
"</body>\n"
"</html>\n";