
#pragma once



static char upload_page[]=
"<!DOCTYPE html>"
"<html>"
"<head>"
"<title>ESP SD Upload</title>"
"<meta charset='utf-8'>"
"</head>"
"<body>"
"<h2>Upload File</h2>"

"<input type='file' id='f'><br><br>"
"<progress id='bar' value='0' max='100' style='width:300px'></progress>"
"<div id='percent'>0%</div><br>"

"<button onclick='upload()'>Upload</button>"
"<pre id='log'></pre>"

"<script>"
"function upload(){"
"  const file=document.getElementById('f').files[0];"
"  if(!file){alert('Select file');return;}"

"  const bar=document.getElementById('bar');"
"  const percent=document.getElementById('percent');"
"  const log=document.getElementById('log');"

"  bar.value=0;"
"  percent.textContent='0%';"
"  log.textContent='Uploading '+file.name+'...';"

"  const xhr=new XMLHttpRequest();"
"  xhr.open('POST','/upload?name='+encodeURIComponent(file.name),true);"
"  xhr.setRequestHeader('Content-Type','application/octet-stream');"

"  xhr.upload.onprogress=function(e){"
"    if(e.lengthComputable){"
"      const p=Math.round((e.loaded/e.total)*100);"
"      bar.value=p;"
"      percent.textContent=p+'%';"
"    }"
"  };"

"  xhr.onload=function(){"
"    if(xhr.status==200){"
"      log.textContent+='\\n✅ '+xhr.responseText;"
"    }else{"
"      log.textContent+='\\n❌ Upload failed';"
"    }"
"  };"

"  xhr.onerror=function(){"
"    log.textContent+='\\n❌ Network error';"
"  };"

"  xhr.send(file);"
"}"
"</script>"
"</body>"
"</html>";



static char main_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n"
"  <title>ESP32</title>\n"
"  <style>\n"
"    * { margin: 0; padding: 0; box-sizing: border-box; }\n"
"    body {\n"
"      font-family: -apple-system, BlinkMacSystemFont, sans-serif;\n"
"      background: #f0f2f5;\n"
"      min-height: 100vh;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      align-items: center;\n"
"      justify-content: center;\n"
"      padding: 15px;\n"
"    }\n"
"    .container {\n"
"      width: 100%;\n"
"      max-width: 500px;\n"
"      text-align: center;\n"
"    }\n"
"    h1 {\n"
"      font-size: 1.5rem;\n"
"      margin-bottom: 20px;\n"
"      color: #1a1a1a;\n"
"    }\n"
"    #coords {\n"
"      font-size: 1.8rem;\n"
"      font-weight: bold;\n"
"      color: #0071e3;\n"
"      background: white;\n"
"      padding: 20px 10px;\n"
"      border-radius: 20px;\n"
"      margin: 15px 0 25px;\n"
"      box-shadow: 0 4px 12px rgba(0,0,0,0.08);\n"
"    }\n"
"    #coords div {\n"
"      margin: 8px 0;\n"
"    }\n"
"    .btn-group {\n"
"      display: flex;\n"
"      gap: 10px;\n"
"      margin: 10px 0;\n"
"      justify-content: center;\n"
"    }\n"
"    .btn {\n"
"      flex: 1;\n"
"      padding: 18px 10px;\n"
"      font-size: 18px;\n"
"      font-weight: 600;\n"
"      border: none;\n"
"      border-radius: 16px;\n"
"      cursor: pointer;\n"
"      touch-action: manipulation;\n"
"      -webkit-tap-highlight-color: transparent;\n"
"    }\n"
"    .btn:active {\n"
"      opacity: 0.9;\n"
"      transform: scale(0.98);\n"
"    }\n"
"    .red { background: #ff3b30; color: white; }\n"
"    .green { background: #34c759; color: white; }\n"
"    .blue { background: #0071e3; color: white; }\n"
"    #status {\n"
"      margin-top: 20px;\n"
"      font-size: 1.1rem;\n"
"      font-weight: bold;\n"
"      min-height: 1.5em;\n"
"    }\n"
"    .online { color: #34c759; }\n"
"    .offline { color: #ff3b30; }\n"
"    h3 {\n"
"      font-size: 1.1rem;\n"
"      color: #666;\n"
"      margin: 15px 0 5px 0;\n"
"      font-weight: 500;\n"
"    }\n"
"    #step-input {\n"
"      width: 100%;\n"
"      padding: 10px;\n"
"      border-radius: 12px;\n"
"      border: 1px solid #ccc;\n"
"      font-size: 16px;\n"
"      margin: 10px 0 20px;\n"
"    }\n"
"    label {\n"
"      display: block;\n"
"      margin-bottom: 6px;\n"
"      font-weight: 500;\n"
"      color: #333;\n"
"    }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"container\">\n"
"    <h1>ДАННЫЕ В РЕАЛЬНОМ ВРЕМЕНИ</h1>\n"
"    \n"
"    <div id=\"coords\">\n"
"      <div>X: <span id=\"x-val\">0</span></div>\n"
"      <div>Y: <span id=\"y-val\">0</span></div>\n"
"      <div>Z: <span id=\"z-val\">0</span></div>\n"
"    </div>\n"
"\n"
"    <label for=\"step-input\">Шаг (мм):</label>\n"
"    <input type=\"number\" id=\"step-input\" value=\"5\" min=\"0.1\" step=\"0.1\">\n"
"    \n"
"    <h3>ГРУППА 1</h3>\n"
"    <div class=\"btn-group\">\n"
"      <button class=\"btn red\" onclick=\"send('cmd1')\">X+</button>\n"
"      <button class=\"btn green\" onclick=\"send('cmd2')\">X-</button>\n"
"      <button class=\"btn blue\" onclick=\"send('cmd3')\">X -> 0</button>\n"
"    </div>\n"
"    \n"
"    <h3>ГРУППА 2</h3>\n"
"    <div class=\"btn-group\">\n"
"      <button class=\"btn red\" onclick=\"send('cmd4')\">Y+</button>\n"
"      <button class=\"btn green\" onclick=\"send('cmd5')\">Y-</button>\n"
"      <button class=\"btn blue\" onclick=\"send('cmd6')\">Y -> 0</button>\n"
"    </div>\n"
"    \n"
"    <h3>ГРУППА 3</h3>\n"
"    <div class=\"btn-group\">\n"
"      <button class=\"btn red\" onclick=\"send('cmd7')\">Z+</button>\n"
"      <button class=\"btn green\" onclick=\"send('cmd8')\">Z-</button>\n"
"      <button class=\"btn blue\" onclick=\"send('cmd9')\">Z -> 0</button>\n"
"    </div>\n"
"    \n"
"    <div id=\"status\" class=\"offline\">ПОДКЛЮЧЕНИЕ...</div>\n"
"  </div>\n"
"\n"
"  <script>\n"
"    let ws;\n"
"    const statusEl = document.getElementById('status');\n"
"    const xEl = document.getElementById('x-val');\n"
"    const yEl = document.getElementById('y-val');\n"
"    const zEl = document.getElementById('z-val');\n"
"\n"
"    function connect() {\n"
"      ws = new WebSocket('ws://' + location.host + '/ws');\n"
"\n"
"      ws.onopen = () => {\n"
"        statusEl.textContent = 'ГОТОВ';\n"
"        statusEl.className = 'online';\n"
"        setInterval(() => {\n"
"          if (ws && ws.readyState === WebSocket.OPEN) {\n"
"            ws.send('get_pos');\n"
"          }\n"
"        }, 20);\n"
"      };\n"
"\n"
"      ws.onmessage = (event) => {\n"
"        try {\n"
"          const data = JSON.parse(event.data);\n"
"          if (typeof data.x === 'number') xEl.textContent = data.x.toFixed(2);\n"
"          if (typeof data.y === 'number') yEl.textContent = data.y.toFixed(2);\n"
"          if (typeof data.z === 'number') zEl.textContent = data.z.toFixed(2);\n"
"        } catch (e) {}\n"
"      };\n"
"\n"
"      ws.onclose = () => {\n"
"        statusEl.textContent = 'ОТКЛЮЧЁН';\n"
"        statusEl.className = 'offline';\n"
"        xEl.textContent = '—';\n"
"        yEl.textContent = '—';\n"
"        zEl.textContent = '—';\n"
"        setTimeout(connect, 2000);\n"
"      };\n"
"    }\n"
"\n"
"    function send(cmd) {\n"
"      if (ws && ws.readyState === WebSocket.OPEN) {\n"
"        const stepInput = document.getElementById('step-input');\n"
"        const step = parseFloat(stepInput.value) || 5.0;\n"
"        ws.send(JSON.stringify({cmd, step}));\n"
"      }\n"
"    }\n"
"\n"
"    window.onload = connect;\n"
"  </script>\n"
"</body>\n"
"</html>";


const char file_select_page[] =
"<!DOCTYPE html>"
"<html>"
"<head>"
"  <meta charset='utf-8'>"
"  <title>G-code files</title>"
"  <style>"
"    li { cursor: pointer; padding: 4px; }"
"    li.selected { background-color: #aaf; }"
"  </style>"
"</head>"
"<body>"
"  <h2>Files on SD card</h2>"
"  <ul id='fileList'></ul>"
"  <button id='selectBtn'>Выбрать</button>"
"  <button id='deleteBtn'>Удалить</button>"
"  <p id='status'></p>"

"  <script>"
"    let selectedFile = null;"
"    const list = document.getElementById('fileList');"
"    const status = document.getElementById('status');"

"    function fetchFiles() {"
"      list.innerHTML = '';"
"      fetch('/files')"
"        .then(r => r.text())"
"        .then(t => {"
"          t.split('\\n').forEach(name => {"
"            if (!name) return;"
"            const li = document.createElement('li');"
"            li.textContent = name;"
"            li.onclick = () => {"
"              // выделяем один файл"
"              document.querySelectorAll('li').forEach(el => el.classList.remove('selected'));"
"              li.classList.add('selected');"
"              selectedFile = name;"
"            };"
"            list.appendChild(li);"
"          });"
"        });"
"    }"

"    document.getElementById('selectBtn').onclick = () => {"
"      if (!selectedFile) { status.textContent = 'Сначала выберите файл'; return; }"
"      fetch('/start', {"
"        method: 'POST',"
"        body: selectedFile"
"      })"
"      .then(r => r.text())"
"      .then(t => { status.textContent = t; });"
"    };"

"    document.getElementById('deleteBtn').onclick = () => {"
"      if (!selectedFile) { status.textContent = 'Сначала выберите файл'; return; }"
"      fetch('/delete', {"
"        method: 'POST',"
"        body: selectedFile"
"      })"
"      .then(r => r.text())"
"      .then(t => { status.textContent = t; fetchFiles(); });"
"    };"

"    fetchFiles();"
"  </script>"
"</body>"
"</html>";
